[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsonwebtoken", "@netlify/blobs"]

# (Optional) Pretty API paths
[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/signups"
  to = "/.netlify/functions/signups"
  status = 200